//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bainaycuatkvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAOCA
    {
        public int MaPhanCa { get; set; }
        public int MaCa { get; set; }
        public Nullable<int> SoTienBanGiao { get; set; }
        public Nullable<int> SoTienThuDuoc { get; set; }
        public Nullable<int> SoTienCatGiu { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CALAMVIEC CALAMVIEC { get; set; }
        public virtual PHANCA PHANCA { get; set; }
    }
}
