//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bainaycuatkvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANGHOA()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
            this.ctphieunhaphangs = new HashSet<ctphieunhaphang>();
            this.CTPHIEUTRAHANGs = new HashSet<CTPHIEUTRAHANG>();
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
        }
    
        public string MaHH { get; set; }
        public string TenHH { get; set; }
        public string MaNH { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> GiaNhap { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public string DonViTinh { get; set; }
        public string MaNCC { get; set; }
        public string MaVach { get; set; }
        public Nullable<int> DinhMuc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> TrangThaiBan { get; set; }
        public Nullable<int> VAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctphieunhaphang> ctphieunhaphangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUTRAHANG> CTPHIEUTRAHANGs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHOMHANG NHOMHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
    }
}
