//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bainaycuatkvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHANCA()
        {
            this.GIAOCAs = new HashSet<GIAOCA>();
        }
    
        public int MaPhanCa { get; set; }
        public Nullable<int> MaCa { get; set; }
        public string NgayLamViec { get; set; }
        public string MaNV { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CALAMVIEC CALAMVIEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAOCA> GIAOCAs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
