//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bainaycuatkvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTRAHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUTRAHANG()
        {
            this.CTPHIEUTRAHANGs = new HashSet<CTPHIEUTRAHANG>();
        }
    
        public string SoPhieuTra { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUTRAHANG> CTPHIEUTRAHANGs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
