//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bainaycuatkvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAPHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUNHAPHANG()
        {
            this.ctphieunhaphangs = new HashSet<ctphieunhaphang>();
        }
    
        public string SoPhieu { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NhaCungCap { get; set; }
        public Nullable<int> GiaNhap { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctphieunhaphang> ctphieunhaphangs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP1 { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
